# Generated by Django 5.0 on 2024-01-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleauthor',
            name='author',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='articleauthor',
            name='profile_picture',
            field=models.ImageField(upload_to='images/profile_pictures/authors/'),
        ),
    ]
