# Generated by Django 5.0 on 2024-01-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articleauthor_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleauthor',
            old_name='profile_picture',
            new_name='author_profile_picture',
        ),
    ]
