# Generated by Django 5.0 on 2024-01-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_picture_for_article',
            field=models.ImageField(blank=True, null=True, upload_to='images/articles/main_picture/', verbose_name='main_picture_for_article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_picture_max_size',
            field=models.ImageField(blank=True, null=True, upload_to='images/articles/main_picture/', verbose_name='article_main_picture_max_size'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_picture_miniature',
            field=models.ImageField(blank=True, null=True, upload_to='images/articles/main_picture/', verbose_name='article_main_picture_miniature'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_picture_preview',
            field=models.ImageField(blank=True, null=True, upload_to='images/articles/main_picture/', verbose_name='article_main_picture_preview'),
        ),
    ]
