# Generated by Django 5.0 on 2024-02-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('public', 'Public'), ('archiv', 'Archiv')], default='draft', max_length=20),
        ),
    ]
