# Generated by Django 5.0 on 2024-01-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_profile_picture_articleauthor_author_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleauthor',
            name='author',
            field=models.CharField(max_length=150, unique=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='articleauthor',
            name='author_profile_picture',
            field=models.ImageField(upload_to='images/profile_pictures/authors/', verbose_name='author profile picture'),
        ),
    ]
