# Generated by Django 5.0 on 2024-01-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_main_picture_for_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleauthor',
            name='profile_picture_thumbnail',
            field=models.ImageField(null=True, upload_to='images/profile_pictures/authors/', verbose_name='profile_picture_thumbnail'),
        ),
    ]
