# Generated by Django 5.0 on 2023-12-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_tags_article_articles_ar_slug_452037_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
