print("### main/articles/migrations/0004_alter_article_status.py")

# Generated by Django 5.0 on 2024-02-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish'), ('archiv', 'Archiv')], default='draft', max_length=20),
        ),
    ]
