# Generated by Django 5.0 on 2023-12-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='slug',
            field=models.CharField(default='', max_length=20),
        ),
    ]
