# Generated by Django 5.0 on 2024-02-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('publish', 'Publish'), ('archive', 'Archive')], default='draft', max_length=20),
        ),
    ]
