# Generated by Django 5.0 on 2024-01-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articleauthor_profile_picture_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleauthor',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
