# Generated by Django 5.0 on 2024-01-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articleauthor_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_picture_high',
            field=models.ImageField(blank=True, null=True, upload_to='articles/main_picture/'),
        ),
        migrations.AddField(
            model_name='article',
            name='main_picture_low',
            field=models.ImageField(blank=True, null=True, upload_to='articles/main_picture/'),
        ),
        migrations.AddField(
            model_name='article',
            name='main_picture_medium',
            field=models.ImageField(blank=True, null=True, upload_to='articles/main_picture/'),
        ),
    ]
