# Generated by Django 5.0 on 2024-01-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articleauthor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleauthor',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
    ]
