# Generated by Django 5.0 on 2024-01-25 17:39

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_articleauthor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='overview',
            field=tinymce.models.HTMLField(verbose_name='article_overview'),
        ),
    ]
