# Generated by Django 5.0 on 2024-01-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_thumbnail_article_main_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='main_picture_medium',
        ),
    ]
