# Generated by Django 5.0 on 2024-03-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publish_date',
            new_name='published',
        ),
    ]
