# Generated by Django 5.0 on 2024-01-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='overview',
            field=models.TextField(verbose_name='article_overview'),
        ),
    ]
