# Generated by Django 5.0 on 2024-04-02 14:18

import articles.models.article_category
import autoslug.fields
import django.db.models.deletion
import taggit.managers
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_publish_date_article_published'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articleauthor', verbose_name='Article Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=articles.models.article_category.ArticleCategory.get_default_category_id, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='article_category', to='articles.articlecategory', verbose_name='Article Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Article main_content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Article Created Date '),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_picture_for_article',
            field=models.ImageField(blank=True, null=True, upload_to='images/articles/main_picture/', verbose_name='Article Main Picture'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_picture_max_size',
            field=models.ImageField(blank=True, null=True, upload_to='images/articles/main_picture/', verbose_name='Article Main Picture Max-Size'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_picture_miniature',
            field=models.ImageField(blank=True, null=True, upload_to='images/articles/main_picture/', verbose_name='Article Main Picture Miniature'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_picture_preview',
            field=models.ImageField(blank=True, null=True, upload_to='images/articles/main_picture/', verbose_name='Article Main Picture Preview'),
        ),
        migrations.AlterField(
            model_name='article',
            name='next_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='articles.article', verbose_name='Next Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='overview',
            field=models.TextField(blank=True, null=True, verbose_name='Article overview'),
        ),
        migrations.AlterField(
            model_name='article',
            name='previous_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='articles.article', verbose_name='Previous Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Article Published Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Article Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('publish', 'Publish'), ('archive', 'Archive')], default='draft', max_length=20, verbose_name='Article Status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Article Tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Article Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Article Updated Date '),
        ),
    ]
