# Generated by Django 5.0 on 2024-01-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_article_main_picture_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_picture',
            field=models.ImageField(upload_to='articles/main_picture/'),
        ),
    ]
