# Generated by Django 5.0 on 2024-01-27 10:44

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='article_main_content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='overview',
            field=models.TextField(blank=True, null=True, verbose_name='article_overview'),
        ),
    ]
