# Generated by Django 5.0 on 2024-01-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_main_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='main_picture',
            new_name='main_picture_for_article',
        ),
    ]
