# Generated by Django 5.0 on 2024-01-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_rename_main_picture_article_main_picture_for_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='main_picture_low',
            new_name='main_picture_miniature',
        ),
    ]
