# Generated by Django 5.0 on 2024-01-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_rename_main_picture_low_article_main_picture_miniature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='main_picture_high',
            new_name='main_picture_max_size',
        ),
    ]
