# Generated by Django 5.0 on 2024-01-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_rename_main_picture_high_article_main_picture_max_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_picture_preview',
            field=models.ImageField(blank=True, null=True, upload_to='articles/main_picture/'),
        ),
    ]
