# Generated by Django 5.0 on 2024-01-27 11:45

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='article_main_content'),
        ),
    ]
