# Generated by Django 5.0 on 2024-01-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_main_picture_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_picture_for_article',
            field=models.ImageField(upload_to='images/articles/main_picture/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_picture_max_size',
            field=models.ImageField(blank=True, null=True, upload_to='images/articless/main_picture/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_picture_miniature',
            field=models.ImageField(blank=True, null=True, upload_to='images/articles/main_picture/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_picture_preview',
            field=models.ImageField(blank=True, null=True, upload_to='images/articles/main_picture/'),
        ),
    ]
