# Generated by Django 5.0 on 2024-01-27 12:26

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_content'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
