# Generated by Django 5.0 on 2024-01-31 12:09

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='article_main_content'),
        ),
    ]
