# Generated by Django 5.0 on 2024-01-19 12:43

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_rename_author_profile_picture_articleauthor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='article_main_content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_picture_for_article',
            field=models.ImageField(upload_to='images/articles/main_picture/', verbose_name='article_main_picture'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_picture_max_size',
            field=models.ImageField(blank=True, null=True, upload_to='images/articles/main_picture/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='overview',
            field=models.TextField(verbose_name='article_overview'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='article_title'),
        ),
    ]
