# Generated by Django 5.0 on 2024-04-02 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0008_alter_article_author_alter_article_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('address', models.CharField(max_length=255, verbose_name='Company Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Company Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Company Email')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('behance_url', models.URLField(blank=True, verbose_name='Behance URL')),
                ('pinterest_url', models.URLField(blank=True, verbose_name='Pinterest URL')),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='HomePageDividerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divider_image', models.ImageField(blank=True, null=True, upload_to='images/homepage/', verbose_name='Divider Section Image')),
                ('divider_text', models.TextField(blank=True, null=True, verbose_name='Divider Section Text')),
                ('divider_link', models.URLField(blank=True, null=True, verbose_name='Divider Section Link')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Page Title')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='images/homepage/', verbose_name='Hero Section Image')),
                ('hero_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hero Section Title')),
                ('hero_link', models.URLField(blank=True, null=True, verbose_name='Hero Section Link')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageIntroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Intro Section Title')),
                ('intro_description', models.TextField(blank=True, null=True, verbose_name='Intro Section Description')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageFeaturedArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_article_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_article_1', to='articles.article', verbose_name='Featured Article 1')),
                ('featured_article_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_article_2', to='articles.article', verbose_name='Featured Article 2')),
                ('featured_article_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_article_3', to='articles.article', verbose_name='Featured Article 3')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageGallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_article_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_article_1', to='articles.article', verbose_name='Home Page Gallery Article 1')),
                ('gallery_article_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_article_2', to='articles.article', verbose_name='Home Page Gallery Article 2')),
                ('gallery_article_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_article_3', to='articles.article', verbose_name='Home Page Gallery Article 3')),
                ('gallery_article_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_article_4', to='articles.article', verbose_name='Home Page Gallery Article 4')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageLatestArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Latest Articles Title')),
                ('latest_description', models.TextField(blank=True, null=True, verbose_name='Latest Articles Description')),
                ('latest_article_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_article_1', to='articles.article', verbose_name='Latest Article 1')),
                ('latest_article_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_article_2', to='articles.article', verbose_name='Latest Article 2')),
                ('latest_article_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_article_3', to='articles.article', verbose_name='Latest Article 3')),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscription Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subscribed User')),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
            },
        ),
        migrations.CreateModel(
            name='HomePageNewsletterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Newsletter Section Title')),
                ('newsletter_description', models.TextField(blank=True, null=True, verbose_name='Newsletter Section Description')),
                ('newsletter_subscribers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_subscribers', to='homepage.newslettersubscriber', verbose_name='Newsletter Subscribers')),
            ],
        ),
    ]
