# Generated by Django 5.0 on 2024-04-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepageherosection',
            old_name='page_title',
            new_name='main_page_title',
        ),
    ]
