# Generated by Django 5.0 on 2024-04-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_page_title_homepageherosection_main_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageherosection',
            name='hero_link_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hero Section Link Title'),
        ),
    ]
