# Generated by Django 5.0 on 2024-04-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_homepageherosection_hero_link_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageherosection',
            name='hero_image',
            field=models.ImageField(blank=True, default='images/homepage/default/hero.jpg', null=True, upload_to='images/homepage/', verbose_name='Hero Section Image'),
        ),
        migrations.AlterField(
            model_name='homepageherosection',
            name='hero_link',
            field=models.URLField(blank=True, default='#!', null=True, verbose_name='Hero Section Link'),
        ),
        migrations.AlterField(
            model_name='homepageherosection',
            name='hero_link_title',
            field=models.CharField(blank=True, default='DISCOVER MORE', max_length=100, null=True, verbose_name='Hero Section Link Title'),
        ),
        migrations.AlterField(
            model_name='homepageherosection',
            name='hero_title',
            field=models.CharField(blank=True, default='Bootstrap 5 Blog - A free template by Bootstrapious', max_length=100, null=True, verbose_name='Hero Section Title'),
        ),
        migrations.AlterField(
            model_name='homepageherosection',
            name='main_page_title',
            field=models.CharField(blank=True, default='Bootstrap Blog', max_length=100, null=True, verbose_name='Page Title'),
        ),
    ]
