# Generated by Django 5.0 on 2024-04-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_homepageherosection_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageherosection',
            name='hero_link_title',
            field=models.CharField(blank=True, default='Discover More', max_length=100, null=True, verbose_name='Hero Section Link Title'),
        ),
    ]
