# Generated by Django 5.0 on 2024-04-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_homepageherosection_hero_link_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageherosection',
            name='main_page_title',
        ),
    ]
