# Generated by Django 5.0 on 2024-04-04 12:48

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_homepageherosection_main_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageherosection',
            name='hero_title',
            field=models.CharField(blank=True, default="Place a nice <strong>introduction</strong> here <strong>to catch reader's attention</strong>. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderi.", max_length=100, null=True, verbose_name='Hero Section Title'),
        ),
        migrations.AlterField(
            model_name='homepageintrosection',
            name='intro_description',
            field=tinymce.models.HTMLField(blank=True, default="Place a nice <strong>introduction</strong> here <strong>to catch reader's attention</strong>. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderi.", null=True, verbose_name='Intro Section Description'),
        ),
        migrations.AlterField(
            model_name='homepageintrosection',
            name='intro_title',
            field=models.CharField(blank=True, default='Some great intro here', max_length=100, null=True, verbose_name='Intro Section Title'),
        ),
    ]
