# Generated by Django 5.0 on 2024-04-05 09:48

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_homepageherosection_hero_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageintrosection',
            name='intro_description',
            field=tinymce.models.HTMLField(blank=True, default="<div style='line-height: 2;'><span style='font-size: 16.5pt; color: rgb(0, 0, 0);'><span style='color: rgb(33, 33, 33);'>Place a nice&nbsp;</span><strong>introduction</strong><span style='color: rgb(33, 33, 33);'>&nbsp;here</span>&nbsp;<strong>to catch reader's attention</strong>. <span style='color: rgb(33, 33, 33);'>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderi.</span></span></div>", null=True, verbose_name='Intro Section Description'),
        ),
        migrations.AlterField(
            model_name='homepageintrosection',
            name='intro_title',
            field=tinymce.models.HTMLField(blank=True, default='Some great intro here', max_length=100, null=True, verbose_name='Intro Section Title'),
        ),
    ]
