# Generated by Django 5.0 on 2024-04-05 10:00

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_homepageintrosection_intro_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageintrosection',
            name='intro_title',
            field=tinymce.models.HTMLField(blank=True, default='Some great intro here', null=True, verbose_name='Intro Section Title'),
        ),
    ]
