# Generated by Django 5.0 on 2024-04-05 10:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_homepageintrosection_intro_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageherosection',
            name='hero_link_title',
            field=tinymce.models.HTMLField(blank=True, default='Discover More', null=True, verbose_name='Hero Section Link Title'),
        ),
        migrations.AlterField(
            model_name='homepageherosection',
            name='hero_title',
            field=tinymce.models.HTMLField(blank=True, default='Bootstrap 5 Blog - A free template by Bootstrapious', null=True, verbose_name='Hero Section Title'),
        ),
        migrations.AlterField(
            model_name='homepageintrosection',
            name='intro_title',
            field=tinymce.models.HTMLField(blank=True, default="<div><span style='font-size: 28px;'><strong>Some great intro here</strong></span></div>", null=True, verbose_name='Intro Section Title'),
        ),
    ]
