# Generated by Django 5.0 on 2024-04-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_homepageherosection_hero_link_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageherosection',
            name='hero_link_title',
            field=models.CharField(blank=True, default='Discover More', max_length=100, null=True, verbose_name='Hero Section Link Title'),
        ),
    ]
