# Generated by Django 5.0 on 2024-04-05 11:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_homepagedividersection_divider_link_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagedividersection',
            name='divider_text',
            field=tinymce.models.HTMLField(blank=True, default='<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</h2>', null=True, verbose_name='Divider Section Text'),
        ),
    ]
