# Generated by Django 5.0 on 2024-04-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_alter_homepagedividersection_divider_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagedividersection',
            name='divider_image',
            field=models.ImageField(blank=True, default='images/homepage/default/divider-bg.jpg', null=True, upload_to='images/homepage/', verbose_name='Divider Section Image'),
        ),
        migrations.AlterField(
            model_name='homepagedividersection',
            name='divider_link',
            field=models.URLField(blank=True, default='#!', null=True, verbose_name='Divider Section Link'),
        ),
        migrations.AlterField(
            model_name='homepagedividersection',
            name='divider_link_title',
            field=models.CharField(blank=True, default='View More', max_length=100, null=True, verbose_name='Hero Section Link Title'),
        ),
    ]
