# Generated by Django 5.0 on 2024-04-05 14:28

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_alter_homepagedividersection_divider_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagelatestarticles',
            name='latest_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Latest Articles Description'),
        ),
        migrations.AlterField(
            model_name='homepagelatestarticles',
            name='latest_title',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Latest Articles Title'),
        ),
    ]
