# Generated by Django 5.0 on 2024-04-06 10:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_alter_homepagelatestarticles_latest_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Company Email'),
        ),
        migrations.AlterField(
            model_name='homepagenewslettersection',
            name='newsletter_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Newsletter Section Description'),
        ),
        migrations.AlterField(
            model_name='homepagenewslettersection',
            name='newsletter_title',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Newsletter Section Title'),
        ),
    ]
