# Generated by Django 5.0 on 2024-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_alter_footersettings_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Company Email'),
        ),
    ]
