# Generated by Django 5.0 on 2024-04-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_alter_footersettings_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='behance_url',
            field=models.URLField(blank=True, null=True, verbose_name='Behance URL'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company Email'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Company Phone'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='pinterest_url',
            field=models.URLField(blank=True, null=True, verbose_name='Pinterest URL'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
    ]
