# Generated by Django 5.0 on 2024-04-07 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_author_alter_article_category_and_more'),
        ('homepage', '0019_alter_footersettings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='footer_article_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_article_1', to='articles.article', verbose_name='Footer Article 1'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='footer_article_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_article_2', to='articles.article', verbose_name='Footer Article 2'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='footer_article_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_article_3', to='articles.article', verbose_name='Footer Article 3'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='name_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Site Link 8 Name'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='url_field',
            field=models.URLField(blank=True, null=True, verbose_name='Site Link 8 URL'),
        ),
    ]
