# Generated by Django 5.0 on 2024-04-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_rename_name_field_footersettings_name_field_8_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field1',
            new_name='url_field_1',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field2',
            new_name='url_field_2',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field3',
            new_name='url_field_3',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field4',
            new_name='url_field_4',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field5',
            new_name='url_field_5',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field6',
            new_name='url_field_6',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field7',
            new_name='url_field_7',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field8',
            new_name='url_field_8',
        ),
    ]
