# Generated by Django 5.0 on 2024-04-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_rename_url_field1_footersettings_url_field_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageherosection',
            name='display_hero_section',
            field=models.BooleanField(default=True, help_text='Check this box to display the Hero Section on the HomePage.', verbose_name='Display Hero Section'),
        ),
    ]
