# Generated by Django 5.0 on 2024-04-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_homepageherosection_display_hero_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='display_footer_section',
            field=models.BooleanField(default=True, verbose_name='Display Footer Section'),
        ),
        migrations.AddField(
            model_name='homepagedividersection',
            name='display_divider_section',
            field=models.BooleanField(default=True, verbose_name='Display Divider Section'),
        ),
        migrations.AddField(
            model_name='homepagefeaturedarticles',
            name='display_featured_section',
            field=models.BooleanField(default=True, verbose_name='Display Featured Section'),
        ),
        migrations.AddField(
            model_name='homepagegallerysection',
            name='display_gallery_section',
            field=models.BooleanField(default=True, verbose_name='Display Gallery Section'),
        ),
        migrations.AddField(
            model_name='homepageintrosection',
            name='display_intro_section',
            field=models.BooleanField(default=True, verbose_name='Display Intro Section'),
        ),
        migrations.AddField(
            model_name='homepagelatestarticles',
            name='display_latest_section',
            field=models.BooleanField(default=True, verbose_name='Display Latest Section'),
        ),
        migrations.AddField(
            model_name='homepagenewslettersection',
            name='display_newsletter_section',
            field=models.BooleanField(default=True, verbose_name='Display Newsletter Section'),
        ),
        migrations.AlterField(
            model_name='homepageherosection',
            name='display_hero_section',
            field=models.BooleanField(default=True, verbose_name='Display Hero Section'),
        ),
    ]
