# Generated by Django 5.0 on 2024-04-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_footersettings_display_footer_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='display_footer_end_section',
            field=models.BooleanField(default=True, verbose_name='Display Footer End Section'),
        ),
    ]
