# Generated by Django 5.0 on 2024-04-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_footersettings_display_footer_end_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='footer_end_left_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='footer_end_right_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='future_end_left_link',
            field=models.URLField(blank=True, default='#!', null=True, verbose_name='Hero Section Link'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='future_end_right_link',
            field=models.URLField(blank=True, default='#!', null=True, verbose_name='Hero Section Link'),
        ),
    ]
