# Generated by Django 5.0 on 2024-04-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_footersettings_footer_end_left_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footersettings',
            old_name='future_end_left_link',
            new_name='future_end_left_link_url',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='future_end_right_link',
            new_name='future_end_right_link_url',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field_1',
            new_name='url_field_1_url',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field_2',
            new_name='url_field_2_url',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field_3',
            new_name='url_field_3_url',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field_4',
            new_name='url_field_4_url',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field_5',
            new_name='url_field_5_url',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field_6',
            new_name='url_field_6_url',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field_7',
            new_name='url_field_7_url',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='url_field_8',
            new_name='url_field_8_url',
        ),
    ]
