# Generated by Django 5.0 on 2024-04-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_rename_future_end_left_link_footersettings_future_end_left_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='footer_end_left_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer-End Left Text'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='footer_end_right_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer-End Right Text'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='future_end_left_link_url',
            field=models.URLField(blank=True, default='#!', null=True, verbose_name='Footer-End Left Link'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='future_end_right_link_url',
            field=models.URLField(blank=True, default='#!', null=True, verbose_name='Footer-End Right Link'),
        ),
    ]
