# Generated by Django 5.0 on 2024-04-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_alter_footersettings_footer_end_left_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='footer_end_left_link_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer-End Left Text'),
        ),
    ]
