# Generated by Django 5.0 on 2024-04-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0030_rename_footer_end_left_link_text_footersettings_end_left_link_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='end_right_link_url',
        ),
    ]
