# Generated by Django 5.0 on 2024-04-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0031_remove_footersettings_end_right_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='end_left_link_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer-End Left Link Text'),
        ),
    ]
