# Generated by Django 5.0 on 2024-04-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0032_alter_footersettings_end_left_link_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='end_left_link_text',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='end_left_link_url',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='end_left_text',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='end_right_text',
        ),
    ]
