# Generated by Django 5.0 on 2024-04-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0034_remove_footersettings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='address_values',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='articles',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='end_line',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='site_links',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='social_media_urls',
            field=models.JSONField(default=dict),
        ),
    ]
