# Generated by Django 5.0 on 2024-04-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0035_footersettings_address_values_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footersettings',
            old_name='social_media_urls',
            new_name='social_media',
        ),
    ]
