# Generated by Django 5.0 on 2024-04-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0037_alter_homepagegallerysection_gallery_article_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagegallerysection',
            name='gallery_article_2',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='homepagegallerysection',
            name='gallery_article_3',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='homepagegallerysection',
            name='gallery_article_4',
            field=models.JSONField(default=dict),
        ),
    ]
