# Generated by Django 5.0 on 2024-01-03 12:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
