# Generated by Django 5.0 on 2024-01-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_profile_image_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_thumbnail',
            field=models.ImageField(null=True, upload_to='images/profile_pictures/users/', verbose_name='profile_picture'),
        ),
    ]
