# Generated by Django 5.0 on 2024-01-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_profile_picture_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(upload_to='images/profile_pictures/users/', verbose_name='profile_picture'),
        ),
    ]
