# Generated by Django 5.0 on 2024-01-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='images/profile_pictures/users/default.jpg', upload_to='images/profile_pictures/users/', verbose_name='profile image'),
        ),
    ]
