# Generated by Django 5.0 on 2024-02-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='linked_author_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
