# Generated by Django 5.0 on 2024-02-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_linked_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sidebar_user_user_menu',
            field=models.BooleanField(default=False),
        ),
    ]
