# Generated by Django 5.0 on 2024-02-18 11:51

import utilities.for_users.ordered_boolean_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_sidebar_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sidebar_category',
            field=utilities.for_users.ordered_boolean_field.OrderedBooleanField(default=True, order=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sidebar_search',
            field=utilities.for_users.ordered_boolean_field.OrderedBooleanField(default=False, order=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sidebar_tags',
            field=utilities.for_users.ordered_boolean_field.OrderedBooleanField(default=True, order=4),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sidebar_user',
            field=utilities.for_users.ordered_boolean_field.OrderedBooleanField(default=True, order=2),
        ),
    ]
