# Generated by Django 5.0 on 2024-02-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_orderedbooleanfield_customuser_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedbooleanfield',
            name='hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
