# Generated by Django 5.0 on 2024-02-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_sidebar_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sidebar',
            field=models.BooleanField(default=True),
        ),
    ]
