# Generated by Django 5.0 on 2024-02-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_orderedbooleanfield_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sidebar_category_navigation',
            field=models.BooleanField(default=True),
        ),
    ]
