# Generated by Django 5.0 on 2024-03-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_sidebar_search_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedBooleanField',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sidebar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sidebar_category_navigation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sidebar_search_options',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sidebar_user_author_menu',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sidebar_user_user_menu',
        ),
    ]
