# Generated by Django 5.0 on 2024-03-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_delete_orderedbooleanfield_remove_customuser_sidebar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sidebar_data',
            field=models.JSONField(default=dict),
        ),
    ]
